//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFactory.Client.ServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SensorData", Namespace="http://schemas.datacontract.org/2004/07/SmartFactory.Models")]
    [System.SerializableAttribute()]
    public partial class SensorData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataHoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SensorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataHora {
            get {
                return this.DataHoraField;
            }
            set {
                if ((this.DataHoraField.Equals(value) != true)) {
                    this.DataHoraField = value;
                    this.RaisePropertyChanged("DataHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Polo {
            get {
                return this.PoloField;
            }
            set {
                if ((object.ReferenceEquals(this.PoloField, value) != true)) {
                    this.PoloField = value;
                    this.RaisePropertyChanged("Polo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SensorId {
            get {
                return this.SensorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SensorIdField, value) != true)) {
                    this.SensorIdField = value;
                    this.RaisePropertyChanged("SensorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unidade {
            get {
                return this.UnidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadeField, value) != true)) {
                    this.UnidadeField = value;
                    this.RaisePropertyChanged("Unidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MachineRule", Namespace="http://schemas.datacontract.org/2004/07/SmartFactory.Models")]
    [System.SerializableAttribute()]
    public partial class MachineRule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionCommandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConditionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RuleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetSensorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ThresholdValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionCommand {
            get {
                return this.ActionCommandField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionCommandField, value) != true)) {
                    this.ActionCommandField = value;
                    this.RaisePropertyChanged("ActionCommand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConditionType {
            get {
                return this.ConditionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ConditionTypeField, value) != true)) {
                    this.ConditionTypeField = value;
                    this.RaisePropertyChanged("ConditionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RuleName {
            get {
                return this.RuleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RuleNameField, value) != true)) {
                    this.RuleNameField = value;
                    this.RaisePropertyChanged("RuleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetSensorId {
            get {
                return this.TargetSensorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetSensorIdField, value) != true)) {
                    this.TargetSensorIdField = value;
                    this.RaisePropertyChanged("TargetSensorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ThresholdValue {
            get {
                return this.ThresholdValueField;
            }
            set {
                if ((this.ThresholdValueField.Equals(value) != true)) {
                    this.ThresholdValueField = value;
                    this.RaisePropertyChanged("ThresholdValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRef.IMachineService")]
    public interface IMachineService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachineService/GetCurrentSensors", ReplyAction="http://tempuri.org/IMachineService/GetCurrentSensorsResponse")]
        SmartFactory.Client.ServiceRef.SensorData[] GetCurrentSensors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachineService/GetCurrentSensors", ReplyAction="http://tempuri.org/IMachineService/GetCurrentSensorsResponse")]
        System.Threading.Tasks.Task<SmartFactory.Client.ServiceRef.SensorData[]> GetCurrentSensorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachineService/GetAllRules", ReplyAction="http://tempuri.org/IMachineService/GetAllRulesResponse")]
        SmartFactory.Client.ServiceRef.MachineRule[] GetAllRules();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachineService/GetAllRules", ReplyAction="http://tempuri.org/IMachineService/GetAllRulesResponse")]
        System.Threading.Tasks.Task<SmartFactory.Client.ServiceRef.MachineRule[]> GetAllRulesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachineService/CreateNewRule", ReplyAction="http://tempuri.org/IMachineService/CreateNewRuleResponse")]
        string CreateNewRule(SmartFactory.Client.ServiceRef.MachineRule newRule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMachineService/CreateNewRule", ReplyAction="http://tempuri.org/IMachineService/CreateNewRuleResponse")]
        System.Threading.Tasks.Task<string> CreateNewRuleAsync(SmartFactory.Client.ServiceRef.MachineRule newRule);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMachineServiceChannel : SmartFactory.Client.ServiceRef.IMachineService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MachineServiceClient : System.ServiceModel.ClientBase<SmartFactory.Client.ServiceRef.IMachineService>, SmartFactory.Client.ServiceRef.IMachineService {
        
        public MachineServiceClient() {
        }
        
        public MachineServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MachineServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MachineServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MachineServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SmartFactory.Client.ServiceRef.SensorData[] GetCurrentSensors() {
            return base.Channel.GetCurrentSensors();
        }
        
        public System.Threading.Tasks.Task<SmartFactory.Client.ServiceRef.SensorData[]> GetCurrentSensorsAsync() {
            return base.Channel.GetCurrentSensorsAsync();
        }
        
        public SmartFactory.Client.ServiceRef.MachineRule[] GetAllRules() {
            return base.Channel.GetAllRules();
        }
        
        public System.Threading.Tasks.Task<SmartFactory.Client.ServiceRef.MachineRule[]> GetAllRulesAsync() {
            return base.Channel.GetAllRulesAsync();
        }
        
        public string CreateNewRule(SmartFactory.Client.ServiceRef.MachineRule newRule) {
            return base.Channel.CreateNewRule(newRule);
        }
        
        public System.Threading.Tasks.Task<string> CreateNewRuleAsync(SmartFactory.Client.ServiceRef.MachineRule newRule) {
            return base.Channel.CreateNewRuleAsync(newRule);
        }
    }
}
